### ISSUE TITLE
Various rendering artifacts

### ISSUE THREAD

**Issue by cHoco** [rhysd/neovim-component#12]
Hello, I've been testing NayoVim again after the HiDPI fix and I've been noticing a various number of artifacts in the rendering. 

1. The line heigh of text doesn't feel right, and sometimes it changes between characters
<img width="444" alt="screen shot 2016-01-08 at 12 45 24" src="https://cloud.githubusercontent.com/assets/85527/12197282/02ec5716-b606-11e5-95c1-d6f6d7c24a8b.png">

2. Characters are drawn even outside they cell 
<img width="127" alt="screen shot 2016-01-08 at 12 46 22" src="https://cloud.githubusercontent.com/assets/85527/12197289/0ae8ee16-b606-11e5-8f64-00d9488b5cad.png">

3. While scrolling parts little pieces of the text are left on the canvas in places where they where before
<img width="630" alt="screen shot 2016-01-08 at 12 46 32" src="https://cloud.githubusercontent.com/assets/85527/12197295/12ed5d9a-b606-11e5-8a19-99cb5faeb030.png">

4. Spacing between character seems wrong
<img width="451" alt="screen shot 2016-01-08 at 12 46 15" src="https://cloud.githubusercontent.com/assets/85527/12197299/17ea5fbe-b606-11e5-8984-578eaaa3bd46.png">

5. When resizing the window the rendering of the canvas just goes wild, part of the canvas turns white, other parts don't render etc...
![screen shot 2016-01-08 at 12 48 27](https://cloud.githubusercontent.com/assets/85527/12197306/240eaf02-b606-11e5-9ce2-7cec8f9181c5.png)

**Comment by rhysd** [comment]
Thank you for reporting them.  I'll fix them one by one.

**Comment by romgrk** [comment]
In case it is of any use, as a reference: http://txtjs.com/

@rhysd were you still planning on not using any external lib for rendering?
 And in any eventuality, were you planning on `unhooking` from the `nvim` GUI rendering at some point? I'm asking because I find it makes less and less sense to let `neovim` handle the syntax and coloration; it would make rendering much more easier.

**Comment by rhysd** [comment]
@romgrk 

Thank you for the pointer to txtjs.  It's interesting and I think I should check it out.

> were you still planning on not using any external lib for rendering?

About pixi.js?  Currently no plan because I thought it might improve performance.  (but actually the bottle neck seemed to be rpc decoding)  However, if txtjs is helpful,  we might consider to use external library again.

> And in any eventuality, were you planning on unhooking from the nvim GUI rendering at some point?

Hmm... I can't imagine what you say.  Could you describe more detail?  It may be good design to separate renderer as interface and enable to add external renderer, but I don't plan it yet because there are still many bugs to fix which have higher priority.

**Comment by rhysd** [comment]
I fixed the coodinate of text on rendering on v0.3.3.  I forgot considering line-height on rendering text...  `<canvas>`'s line-height is fixed to `1.2` and we must consider it on rendering.

Now,

> 1. The line heigh of text doesn't feel right, and sometimes it changes between characters

I feel this was fixed as below.

<img width="186" alt="2016-01-19 18 48 16" src="https://cloud.githubusercontent.com/assets/823277/12415141/411a6cfa-bedd-11e5-84c1-be2ac0697dd0.png">

Because of the same reason,

> 2. Characters are drawn even outside they cell 

and

> 4. Spacing between character seems wrong

may be fixed.  If you can,  please check them.  In case 2., I don't know how to input the 'L N' font and in case 4., it is a patched font so I can't check it easily.

And I can't reproduce 3. yet.

**Comment by rhysd** [comment]
Task list.

- [x] The line heigh of text doesn't feel right, and sometimes it changes between characters
- [ ] Characters are drawn even outside they cell
- [ ] While scrolling parts little pieces of the text are left on the canvas in places where they where before **I can't repro**
- [ ] Spacing between character seems wrong
- [ ] When resizing the window the rendering of the canvas just goes wild, part of the canvas turns white, other parts don't render etc...

**Comment by rhysd** [comment]
I fixed resizing on v0.3.7.

**Comment by cHoco** [comment]
Hey, sorry for not getting back to you sooner! Just pulled the new changes and tested around. Line height between characters seems to be fixed, but when scrolling the rendering still gets messed up :( and text isn't aligned anymore. But I think the problem must be somewhere else. 
Character still render outside of their cell, to reproduce it easily install the vim-airline plugin open a textfiles and just scroll around, the line number on the statusbar should render outside its cell as shown in my first screenshot. 

Resizing seems to be fixed, but it still has some problems, for example if I keep resizing instead of just maximizing or minimizing the window the window still ends up white. 

When I finish my exams next month I plan on helping out in fixing these issue because I think this project is really important for the vim future :D 
For reference there's another project implementing neovim in Electron here https://github.com/coolwanglu/neovim-e and after trying it out I can confirm that it has none of the issues I mentioned in this post, so we may take a look at how it perform rendering and resizing and figure out what we've been missing!

**Comment by rhysd** [comment]
Thank you for confirming.  Very helpful :smile:

Hmm...  Some problems don't occur in my environment and do occur in yours.  'outside the cell' problem occurs, but both scrolling and resizing are OK in my environment.  I guess they're problem related to font.  Could you tell me what font you're using?

> For reference there's another project implementing neovim in Electron here
> https://github.com/coolwanglu/neovim-e and after trying it out I can confirm that it has none of the issues 

It must be also helpful!  

> When I finish my exams next month I plan on helping out in fixing these issue

It's so helpful!  I have full-time job and I can only write code for my project at night after work :pensive:

**Comment by cHoco** [comment]
> Hmm... Some problems don't occur in my environment and do occur in yours. 'outside the cell' problem > occurs, but both scrolling and maximizing are OK in my environment. I guess they're problem related to > font. Could you tell me what font you're using?

It's a tweaked version of Source Code Pro, I got it in my dotfiles repository: https://github.com/cHoco/dotFiles/blob/master/coding-fonts/source-code-pro/Source%20Code%20Pro%20plus%20Devicons.otf

**Comment by rhysd** [comment]
Thsnks!

And I seemed to be able to reproduce the scroll issue.

![2016-01-22 20 16 46](https://cloud.githubusercontent.com/assets/823277/12509371/4eb0a482-c145-11e5-9eb0-3cc58576c03d.png)

**Comment by rhysd** [comment]
I fixed rendering problems on truncating height of region at v0.4.0.

> Characters are drawn even outside they cell

and

> While scrolling parts little pieces of the text are left on the canvas in places where they where before

seem to be fixed in my environment (MacBook Pro Retina 2015). Could you check this fix?

**Comment by cHoco** [comment]
Just checked and I think it is fixed indeed :dancer:
Thank you again for your hard work! :smile:

**Comment by rhysd** [comment]
Thank you very much for confirming.
I'll update NyaoVim's dependency today!
